/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useEffect } from 'react';

export default function Character(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('./model.gltf');
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions.PortalOpen.play();
	});
	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			castShadow={true}
			rotation={[0, -1.2, 0]}>
			<group scale={1.91}>
				<primitive object={nodes.root} />
				<skinnedMesh
					geometry={nodes.druid.geometry}
					material={materials.color_main}
					skeleton={nodes.druid.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(
	'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf'
);
